services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - "2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"   # optional (host tooling)

  dd-module-kafka-producer:
    build:
      context: ./dd-module-kafka-producer
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      - QUARKUS_HTTP_PORT=8081
      - DD_PORT=8081
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DD_PROCESSOR_BASE_URL=http://dd-module-kafka-processor:8082
      - DD_DLQ_BASE_URL=http://dd-module-dlq-service:8083
    depends_on:
      - kafka
    ports:
      - "8081:8081"

  dd-module-kafka-processor:
    build:
      context: ./dd-module-kafka-processor
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      - QUARKUS_HTTP_PORT=8082
      - DD_PORT=8082
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DD_DLQ_BASE_URL=http://dd-module-dlq-service:8083
    depends_on:
      - kafka
    ports:
      - "8082:8082"

  dd-module-dlq-service:
    build:
      context: ./dd-module-dlq-service
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      - QUARKUS_HTTP_PORT=8083
      - DD_PORT=8083
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    ports:
      - "8083:8083"

  dd-pack:
    build:
      context: ./dd-pack
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      - QUARKUS_HTTP_PORT=8080
      - DD_PORT=8080
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DD_PRODUCER_BASE_URL=http://dd-module-kafka-producer:8081
      - DD_PROCESSOR_BASE_URL=http://dd-module-kafka-processor:8082
      - DD_DLQ_BASE_URL=http://dd-module-dlq-service:8083
    depends_on:
      - kafka
    ports:
      - "8080:8080"